project:
  type: website
  output-dir: docs

website:
  title: "Dan's Data Viz"
  site-url: "https://dmacguigan.github.io/DansDataViz/"
  description: "Blog of various data visualization side projects"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/dmacguigan
      - icon: linkedin
        href: https://www.linkedin.com/in/dmacguigan
      - icon: rss
        href: index.xml
format:
  html:
    theme: darkly
    css: styles.css

execute:
  freeze: true

